tunnel: d33c3aec-40bc-4571-93f4-26afa64964bc
credentials-file: C:\Users\lenovo\.cloudflared\d33c3aec-40bc-4571-93f4-26afa64964bc.json

ingress:
  # Route n8n subdomain ke localhost:5678
  - hostname: n8n.devai.sbs
    service: http://localhost:5678
  
  # Route webhook subdomain ke WebApp
  - hostname: webhook.devai.sbs
    service: http://localhost:3000
  
  # Catch-all rule (HARUS di akhir)
  - service: http_status:404
